[build-system]
requires = ["setuptools>=61", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "FAOV"
version = "0.1.0"
description = "Fast implementation of AOV algorithm for period fitting."
requires-python = ">=3.10"
dependencies = [
  "numpy>=1.22.3"
]

